language: php
sudo: false
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
php:
  - 7.3
services:
  - mysql
before_install:
    - sudo service mysql restart
    - mysql -e 'create database wptest;'
    - mysql -e "CREATE USER 'wptest'@'localhost' IDENTIFIED BY 'wptest';"
    - mysql -e "GRANT ALL ON wptest.* TO 'wptest'@'localhost';"
    - mkdir -p tests/code_coverage/
install:
  - composer install
script:
 - php vendor/bin/phpunit
after_success:
  - sh -c 'if( [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ); then php vendor/bin/php-coveralls -v; fi;'
